# Site settings
title: Bob Frank
email: bob.frank@yale.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bobfrank1.github.io" # the base hostname & protocol for your site
# twitter_username: bob_frank
# github_username:  bobfrank1

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""